#!/bin/bash
echo "# simple_shell" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:wisteen/simple_shell.git
git push -u origin main
